export const properties = [
  {
    id: 1,
    name: "Maple Street Duplex",
    address: "1234 Maple Street",
    city: "Vancouver",
    province: "BC",
    postalCode: "V6B 1A1",
    propertyType: "Duplex",
    unitCount: 2,
    status: "Active",
    notes: "Recently renovated kitchen and bathrooms"
  },
  {
    id: 2,
    name: "Richmond Apartment",
    address: "5678 Garden City Road",
    city: "Richmond",
    province: "BC",
    postalCode: "V6Y 2L5",
    propertyType: "Apartment",
    unitCount: 8,
    status: "Active",
    notes: "4-story building with elevator"
  },
  {
    id: 3,
    name: "Oakridge Rental Home",
    address: "910 Oak Street",
    city: "Vancouver",
    province: "BC",
    postalCode: "V5Z 3Y8",
    propertyType: "Single Family",
    unitCount: 1,
    status: "Active",
    notes: "Large backyard, pet-friendly"
  }
];

export const units = [
  {
    id: 1,
    unitNumber: "A",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    tenantId: 1,
    tenantName: "Sarah Thompson",
    rent: 2200,
    status: "Occupied",
    leaseStart: "2025-01-01",
    leaseEnd: "2026-01-01",
    notes: "Upper unit"
  },
  {
    id: 2,
    unitNumber: "B",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    tenantId: 2,
    tenantName: "Daniel Reed",
    rent: 2100,
    status: "Occupied",
    leaseStart: "2025-03-01",
    leaseEnd: "2026-03-01",
    notes: "Lower unit"
  },
  {
    id: 3,
    unitNumber: "101",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    tenantId: 3,
    tenantName: "Maria Lopez",
    rent: 1800,
    status: "Occupied",
    leaseStart: "2024-06-01",
    leaseEnd: "2026-06-01",
    notes: "Ground floor"
  },
  {
    id: 4,
    unitNumber: "102",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    tenantId: null,
    tenantName: null,
    rent: 1850,
    status: "Vacant",
    leaseStart: null,
    leaseEnd: null,
    notes: "Available June 1st"
  },
  {
    id: 5,
    unitNumber: "201",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    tenantId: 4,
    tenantName: "James Chen",
    rent: 1900,
    status: "Occupied",
    leaseStart: "2025-01-15",
    leaseEnd: "2026-06-15",
    notes: "Second floor corner unit"
  },
  {
    id: 6,
    unitNumber: "Main",
    propertyId: 3,
    propertyName: "Oakridge Rental Home",
    tenantId: null,
    tenantName: null,
    rent: 3200,
    status: "Vacant",
    leaseStart: null,
    leaseEnd: null,
    notes: "Available immediately"
  }
];

export const tenants = [
  {
    id: 1,
    fullName: "Sarah Thompson",
    email: "sarah.thompson@email.com",
    phone: "(604) 555-0123",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    unitId: 1,
    unitNumber: "A",
    leaseStart: "2025-01-01",
    leaseEnd: "2026-01-01",
    leaseStatus: "Active",
    notes: "Preferred contact via email"
  },
  {
    id: 2,
    fullName: "Daniel Reed",
    email: "daniel.reed@email.com",
    phone: "(604) 555-0124",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    unitId: 2,
    unitNumber: "B",
    leaseStart: "2025-03-01",
    leaseEnd: "2026-03-01",
    leaseStatus: "Active",
    notes: "Works night shifts"
  },
  {
    id: 3,
    fullName: "Maria Lopez",
    email: "maria.lopez@email.com",
    phone: "(604) 555-0125",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    unitId: 3,
    unitNumber: "101",
    leaseStart: "2024-06-01",
    leaseEnd: "2026-06-01",
    leaseStatus: "Active",
    notes: "Long-term tenant, always pays on time"
  },
  {
    id: 4,
    fullName: "James Chen",
    email: "james.chen@email.com",
    phone: "(604) 555-0126",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    unitId: 5,
    unitNumber: "201",
    leaseStart: "2025-01-15",
    leaseEnd: "2026-06-15",
    leaseStatus: "Active",
    notes: "Has one cat"
  },
  {
    id: 5,
    fullName: "Emily Watson",
    email: "emily.watson@email.com",
    phone: "(604) 555-0127",
    propertyId: null,
    propertyName: null,
    unitId: null,
    unitNumber: null,
    leaseStart: null,
    leaseEnd: null,
    leaseStatus: "No Unit Assigned",
    notes: "Interested in Oakridge property"
  }
];

export const maintenanceTickets = [
  {
    id: 1,
    title: "Kitchen sink leaking",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    unitId: 1,
    unitNumber: "A",
    tenantId: 1,
    tenantName: "Sarah Thompson",
    category: "Plumbing",
    priority: "High",
    status: "In Progress",
    description: "Water dripping from under the kitchen sink. Seems to be coming from the P-trap.",
    createdDate: "2026-05-08",
    notes: "Plumber scheduled for May 12"
  },
  {
    id: 2,
    title: "Furnace not heating",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    unitId: 3,
    unitNumber: "101",
    tenantId: 3,
    tenantName: "Maria Lopez",
    category: "HVAC",
    priority: "High",
    status: "New",
    description: "Furnace is running but not producing heat. Tenant reports cold air coming from vents.",
    createdDate: "2026-05-09",
    notes: "HVAC technician contacted"
  },
  {
    id: 3,
    title: "Broken window lock",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    unitId: 2,
    unitNumber: "B",
    tenantId: 2,
    tenantName: "Daniel Reed",
    category: "Security",
    priority: "Medium",
    status: "New",
    description: "Lock on bedroom window is broken and won't latch properly.",
    createdDate: "2026-05-10",
    notes: "Will visit property this week"
  },
  {
    id: 4,
    title: "Dishwasher not draining",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    unitId: 5,
    unitNumber: "201",
    tenantId: 4,
    tenantName: "James Chen",
    category: "Appliance",
    priority: "Low",
    status: "Completed",
    description: "Dishwasher fills but doesn't drain. Water remains at bottom after cycle.",
    createdDate: "2026-04-28",
    notes: "Replaced drain pump on May 2"
  },
  {
    id: 5,
    title: "Smoke detector chirping",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    unitId: 3,
    unitNumber: "101",
    tenantId: 3,
    tenantName: "Maria Lopez",
    category: "General",
    priority: "Low",
    status: "Completed",
    description: "Smoke detector beeping every few minutes.",
    createdDate: "2026-05-01",
    notes: "Replaced battery"
  }
];

export const documents = [
  {
    id: 1,
    name: "Lease Agreement - Sarah Thompson",
    documentType: "Lease",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    unitId: 1,
    unitNumber: "A",
    tenantId: 1,
    tenantName: "Sarah Thompson",
    uploadDate: "2024-12-15",
    notes: "1-year lease starting Jan 2025"
  },
  {
    id: 2,
    name: "Move-in Inspection - Unit A",
    documentType: "Inspection",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    unitId: 1,
    unitNumber: "A",
    tenantId: 1,
    tenantName: "Sarah Thompson",
    uploadDate: "2025-01-01",
    notes: "Completed with tenant present"
  },
  {
    id: 3,
    name: "Lease Agreement - Daniel Reed",
    documentType: "Lease",
    propertyId: 1,
    propertyName: "Maple Street Duplex",
    unitId: 2,
    unitNumber: "B",
    tenantId: 2,
    tenantName: "Daniel Reed",
    uploadDate: "2025-02-15",
    notes: "1-year lease starting March 2025"
  },
  {
    id: 4,
    name: "Lease Agreement - Maria Lopez",
    documentType: "Lease",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    unitId: 3,
    unitNumber: "101",
    tenantId: 3,
    tenantName: "Maria Lopez",
    uploadDate: "2024-05-15",
    notes: "2-year lease"
  },
  {
    id: 5,
    name: "30-Day Notice - Unit 102",
    documentType: "Notice",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    unitId: 4,
    unitNumber: "102",
    tenantId: null,
    tenantName: null,
    uploadDate: "2026-04-15",
    notes: "Previous tenant gave notice"
  },
  {
    id: 6,
    name: "Property Tax Assessment 2026",
    documentType: "Other",
    propertyId: 2,
    propertyName: "Richmond Apartment",
    unitId: null,
    unitNumber: null,
    tenantId: null,
    tenantName: null,
    uploadDate: "2026-01-10",
    notes: "Annual property tax"
  }
];
